name = "colo-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route_name = "colo.do/*"
compatibility_date = "2022-07-18"

[durable_objects]
bindings = [{name = "COLO", class_name = "Colo"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Colo"]
