name = "colo-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*/*", zone_name = "colo.do" }
main = "worker.js"
compatibility_date = "2022-07-18"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

kv_namespaces = [
  { binding = "SOURCES", id = "123a0eb73b3d464891d0b39c35eb461a", preview_id = "123a0eb73b3d464891d0b39c35eb461a" }
]

[durable_objects]
bindings = [{name = "COLO", class_name = "Colo"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Colo"]
